[package]
name = "whoami_web"
edition = "2021"
rust-version = "1.75"

[lib]
crate-type = ["cdylib", "rlib"]

# The web panic hook crate provides a visual display during panics
[dependencies.web_panic_hook]
version = "0.1.0"
optional = true

# wasm-bindgen lets us export our main function to the javascript that runs the
# web assembly module.
[dependencies.wasm-bindgen]
version = "0.2.117"

# The `web-sys` crate lets us log in the web console.
[dependencies.web-sys]
version = "0.3.94"
features = ["console"]

# `whoami` - the crate we're testing!
[dependencies.whoami]
path = "../whoami"

[features]
default = ["web_panic_hook"]
