on: [push, pull_request]

name: tests

env:
  RUSTUP_AUTO_INSTALL: 0

jobs:
  building-and-clippy-checks:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        tc: [1.65.0, stable, beta, nightly]
        cc:
        - x86_64-unknown-linux-gnu
        - x86_64-unknown-illumos
        - x86_64-unknown-redox
        - wasm32-unknown-unknown
        - aarch64-linux-android
        - i686-pc-windows-gnu
        - i686-unknown-freebsd
        - i686-unknown-linux-gnu
        - wasm32-wasip1
        - x86_64-apple-darwin
        rf: [RUSTFLAGS=""]
        include:
        - os: ubuntu-latest
          cc: wasm32-unknown-unknown
          rf: [RUSTFLAGS="--cfg daku"]
        - os: ubuntu-latest
          tc: 1.65.0
          cc: wasm32-wasi
        - tc: nightly
          up: cargo update
        - os: macos-latest
          tc: 1.65.0
          cc: aarch64-apple-ios
        - os: macos-latest
          tc: stable
          cc: aarch64-apple-ios
        - os: macos-latest
          tc: beta
          cc: aarch64-apple-ios
        - os: macos-latest
          tc: nightly
          cc: aarch64-apple-ios
        exclude:
        - tc: 1.65.0
          cc: wasm32-wasip1
    steps:
    - uses: taiki-e/checkout-action@v1
    - run: rustup set profile minimal
    - run: rustup default ${{ matrix.tc }}
    - run: rustup component add clippy
    - run: rustup target add ${{ matrix.cc }}
    - if: ${{ matrix.up }}
      run: ${{ matrix.up }}
    - if: ${{ matrix.up }}
      run: ${{ matrix.rf }} cargo clippy --target=${{ matrix.cc }} -p whoami -- -D warnings
    - run: ${{ matrix.rf }} cargo build --target=${{ matrix.cc }} -p whoami
  # can be merged with build-and-clippy in whoami 2.2
  building-and-clippy-checks-no-std:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        tc: [1.81.0, stable, beta, nightly]
        cc:
        - x86_64-unknown-linux-gnu
        - x86_64-unknown-illumos
        - x86_64-unknown-redox
        - wasm32-unknown-unknown
        - aarch64-linux-android
        - i686-pc-windows-gnu
        - i686-unknown-freebsd
        - i686-unknown-linux-gnu
        - wasm32-wasip1
        - x86_64-apple-darwin
        rf: [RUSTFLAGS=""]
        include:
        - os: ubuntu-latest
          cc: wasm32-unknown-unknown
          rf: RUSTFLAGS="--cfg daku"
        - tc: nightly
          up: cargo update
        - os: macos-latest
          tc: 1.81.0
          cc: aarch64-apple-ios
        - os: macos-latest
          tc: stable
          cc: aarch64-apple-ios
        - os: macos-latest
          tc: beta
          cc: aarch64-apple-ios
        - os: macos-latest
          tc: nightly
          cc: aarch64-apple-ios
    steps:
    - uses: taiki-e/checkout-action@v1
    - run: rustup set profile minimal
    - run: rustup default ${{ matrix.tc }}
    - run: rustup component add clippy
    - run: rustup target add ${{ matrix.cc }}
    - if: ${{ matrix.up }}
      run: ${{ matrix.up }}
    - if: ${{ matrix.up }}
      run: ${{ matrix.rf }} cargo clippy --target=${{ matrix.cc }} --no-default-features -p whoami -- -D warnings
    - run: ${{ matrix.rf }} cargo build --target=${{ matrix.cc }} --no-default-features -p whoami 
  testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        tc: [1.65.0, stable, beta, nightly]
        include:
        - tc: nightly
          up: cargo update
    steps:
    - uses: taiki-e/checkout-action@v1
    - run: rustup set profile minimal
    - run: rustup default ${{ matrix.tc }}
    - run: rustup component add rustfmt
    - if: ${{ matrix.up }}
      run: ${{ matrix.up }}
    - run: cargo fmt --check
    - run: cargo doc -p whoami
    - run: cargo test --all
